import assert from "node:assert/strict";
import test from "node:test";

import type { FactoryPlanningData } from "@/lib/order-planning";
import { applyFactoryWorkflowState } from "@/lib/factory-workflow-logic";
import { defaultProductPreparationStages } from "@/lib/production-planning";

test("cancelled orders remain visible in pedidos and leave production/expedition queues", () => {
  const planning: FactoryPlanningData = {
    referenceDate: "2026-03-18",
    orders: [
      {
        id: "order-1",
        code: "PD-0001",
        storeId: "store-1",
        storeName: "Loja A",
        orderedAt: "18/03/2026 08:00",
        dPlusLabel: "D+1",
        deliveryDate: "2026-03-19",
        deliveryDateLabel: "19/03/2026",
        productionDateLabel: "19/03/2026",
        itemsCount: 1,
        totalKg: 12,
        opsLabel: "-",
        releasedToProduction: false,
        availableForRelease: true,
        workflowProgress: 0,
        status: "em_espera",
      },
    ],
    orderItems: [
      {
        id: "item-1",
        orderId: "order-1",
        orderCode: "PD-0001",
        storeId: "store-1",
        storeName: "Loja A",
        orderedAt: "18/03/2026 08:00",
        baseDate: "2026-03-18",
        deliveryDate: "2026-03-19",
        saleDate: "2026-03-19",
        productionDate: "2026-03-19",
        delayed: false,
        productId: "product-1",
        productCode: "PR-0001",
        productName: "Produto A",
        lineId: "line-1",
        lineName: "Linha A",
        sectorId: "sector-1",
        sectorName: "Setor A",
        scheduleId: "schedule-1",
        scheduleCode: "SL-0001",
        scheduleName: "Linha Executora",
        requestedQuantity: 12,
        requestedUnit: "Kg",
        internalKg: 12,
        expeditionUnit: "Kg",
        expeditionQuantityRaw: 12,
        expeditionQuantity: 12,
        canPlan: true,
        availableForRelease: true,
        releasedToProduction: false,
        productionItemKey: "2026-03-19|sector-1|line-1|schedule-1|product-1",
        productionItemStatus: null,
        preparationStages: [...defaultProductPreparationStages],
        workflowProgress: 0,
        opCode: null,
        status: "em_espera",
      },
    ],
    productionOrders: [],
    expedition: [
      {
        id: "exp-1",
        orderId: "order-1",
        orderCode: "PD-0001",
        storeId: "store-1",
        storeName: "Loja A",
        deliveryDate: "2026-03-19",
        deliveryDateLabel: "19/03/2026",
        totalKg: 12,
        itemsCount: 1,
        itemsSummary: "1 item",
        releasedToProduction: false,
        workflowProgress: 0,
        status: "em_espera",
        items: [
          {
            itemId: "item-1",
            productId: "product-1",
            productCode: "PR-0001",
            productName: "Produto A",
            requestedQuantity: 12,
            requestedUnit: "Kg",
            internalKg: 12,
            expeditionQuantityRaw: 12,
            expeditionQuantity: 12,
            expeditionUnit: "Kg",
            productionDate: "2026-03-19",
            saleDate: "2026-03-19",
            workflowProgress: 0,
          },
        ],
      },
    ],
    expeditionItems: [],
    productionDates: ["2026-03-19"],
    deliveryDates: ["2026-03-19"],
  };

  const result = applyFactoryWorkflowState(planning, {
    isReleased: () => false,
    isCancelled: (orderId) => orderId === "order-1",
    resolveProductionItemStatus: () => null,
  });

  assert.equal(result.orders[0]?.status, "cancelado");
  assert.equal(result.orders[0]?.availableForRelease, false);
  assert.equal(result.productionOrders.length, 0);
  assert.equal(result.expedition.length, 0);
  assert.equal(result.orderItems[0]?.status, "cancelado");
});

test("multiple orders on the same line and day collapse into one production order while expedition stays per order", () => {
  const planning: FactoryPlanningData = {
    referenceDate: "2026-03-18",
    orders: [
      {
        id: "order-1",
        code: "PD-0009",
        storeId: "store-1",
        storeName: "Loja A",
        orderedAt: "18/03/2026 08:00",
        orderedAtKey: "2026-03-18",
        dPlusLabel: "D+2",
        deliveryDate: "2026-03-20",
        deliveryDateLabel: "20/03/2026",
        productionDateLabel: "20/03/2026",
        itemsCount: 1,
        totalKg: 10,
        opsLabel: "-",
        releasedToProduction: false,
        availableForRelease: true,
        workflowProgress: 0,
        status: "em_espera",
      },
      {
        id: "order-2",
        code: "PD-0010",
        storeId: "store-2",
        storeName: "Loja B",
        orderedAt: "18/03/2026 08:15",
        orderedAtKey: "2026-03-18",
        dPlusLabel: "D+2",
        deliveryDate: "2026-03-20",
        deliveryDateLabel: "20/03/2026",
        productionDateLabel: "20/03/2026",
        itemsCount: 1,
        totalKg: 12,
        opsLabel: "-",
        releasedToProduction: false,
        availableForRelease: true,
        workflowProgress: 0,
        status: "em_espera",
      },
    ],
    orderItems: [
      {
        id: "item-1",
        orderId: "order-1",
        orderCode: "PD-0009",
        storeId: "store-1",
        storeName: "Loja A",
        orderedAt: "18/03/2026 08:00",
        baseDate: "2026-03-18",
        deliveryDate: "2026-03-20",
        saleDate: "2026-03-20",
        productionDate: "2026-03-20",
        delayed: false,
        productId: "product-pan",
        productCode: "PR-PAO",
        productName: "Pao Frances",
        lineId: "line-pan",
        lineName: "Linha de Paes",
        sectorId: "sector-pan",
        sectorName: "Panificacao",
        scheduleId: "schedule-pan",
        scheduleCode: "SL-PAN",
        scheduleName: "Linha Panificacao",
        requestedQuantity: 10,
        requestedUnit: "Kg",
        internalKg: 10,
        expeditionUnit: "Kg",
        expeditionQuantityRaw: 10,
        expeditionQuantity: 10,
        canPlan: true,
        availableForRelease: true,
        releasedToProduction: false,
        productionItemKey: "2026-03-20|line-pan|schedule-pan|product-pan",
        productionItemStatus: null,
        preparationStages: [...defaultProductPreparationStages],
        workflowProgress: 0,
        opCode: null,
        status: "em_espera",
      },
      {
        id: "item-2",
        orderId: "order-2",
        orderCode: "PD-0010",
        storeId: "store-2",
        storeName: "Loja B",
        orderedAt: "18/03/2026 08:15",
        baseDate: "2026-03-18",
        deliveryDate: "2026-03-20",
        saleDate: "2026-03-20",
        productionDate: "2026-03-20",
        delayed: false,
        productId: "product-pan-2",
        productCode: "PR-FORMA",
        productName: "Pao de Forma",
        lineId: "line-pan",
        lineName: "Linha de Paes",
        sectorId: "sector-pan",
        sectorName: "Panificacao",
        scheduleId: "schedule-pan",
        scheduleCode: "SL-PAN",
        scheduleName: "Linha Panificacao",
        requestedQuantity: 12,
        requestedUnit: "Kg",
        internalKg: 12,
        expeditionUnit: "Kg",
        expeditionQuantityRaw: 12,
        expeditionQuantity: 12,
        canPlan: true,
        availableForRelease: true,
        releasedToProduction: false,
        productionItemKey: "2026-03-20|line-pan|schedule-pan|product-pan-2",
        productionItemStatus: null,
        preparationStages: [...defaultProductPreparationStages],
        workflowProgress: 0,
        opCode: null,
        status: "em_espera",
      },
    ],
    productionOrders: [],
    expedition: [
      {
        id: "exp-1",
        orderId: "order-1",
        orderCode: "PD-0009",
        storeId: "store-1",
        storeName: "Loja A",
        deliveryDate: "2026-03-20",
        deliveryDateLabel: "20/03/2026",
        totalKg: 10,
        itemsCount: 1,
        itemsSummary: "1 item",
        releasedToProduction: false,
        workflowProgress: 0,
        status: "em_espera",
        items: [
          {
            itemId: "item-1",
            productId: "product-pan",
            productCode: "PR-PAO",
            productName: "Pao Frances",
            requestedQuantity: 10,
            requestedUnit: "Kg",
            internalKg: 10,
            expeditionQuantityRaw: 10,
            expeditionQuantity: 10,
            expeditionUnit: "Kg",
            productionDate: "2026-03-20",
            saleDate: "2026-03-20",
            workflowProgress: 0,
          },
        ],
      },
      {
        id: "exp-2",
        orderId: "order-2",
        orderCode: "PD-0010",
        storeId: "store-2",
        storeName: "Loja B",
        deliveryDate: "2026-03-20",
        deliveryDateLabel: "20/03/2026",
        totalKg: 12,
        itemsCount: 1,
        itemsSummary: "1 item",
        releasedToProduction: false,
        workflowProgress: 0,
        status: "em_espera",
        items: [
          {
            itemId: "item-2",
            productId: "product-pan-2",
            productCode: "PR-FORMA",
            productName: "Pao de Forma",
            requestedQuantity: 12,
            requestedUnit: "Kg",
            internalKg: 12,
            expeditionQuantityRaw: 12,
            expeditionQuantity: 12,
            expeditionUnit: "Kg",
            productionDate: "2026-03-20",
            saleDate: "2026-03-20",
            workflowProgress: 0,
          },
        ],
      },
    ],
    expeditionItems: [],
    productionDates: ["2026-03-20"],
    deliveryDates: ["2026-03-20"],
  };

  const result = applyFactoryWorkflowState(planning, {
    isReleased: (orderId) => orderId === "order-1" || orderId === "order-2",
    isCancelled: () => false,
    resolveProductionItemStatus: () => null,
  });

  assert.equal(result.productionOrders.length, 1);
  assert.deepEqual(result.productionOrders[0]?.orderCodes, ["PD-0009", "PD-0010"]);
  assert.equal(result.productionOrders[0]?.ordersCount, 2);
  assert.equal(result.productionOrders[0]?.itemsCount, 2);
  assert.equal(new Set(result.orderItems.map((item) => item.opCode).filter(Boolean)).size, 1);
  assert.equal(result.orders[0]?.releasedToProduction, true);
  assert.equal(result.orders[1]?.releasedToProduction, true);
  assert.equal(result.orders[0]?.opsLabel, result.productionOrders[0]?.code);
  assert.equal(result.orders[1]?.opsLabel, result.productionOrders[0]?.code);
  assert.equal(result.expedition.length, 2);
  assert.deepEqual(
    result.expedition.map((row) => row.orderCode).sort((a, b) => a.localeCompare(b)),
    ["PD-0009", "PD-0010"],
  );
});
