import {
  buildEmptyAddress,
  buildProfile,
  type ManagedUser,
} from "../../src/lib/admin-users";
import { buildDefaultPermissions } from "../../src/lib/permission-modules";

export const initialUsers: ManagedUser[] = [
  {
    id: "user-master",
    tenantId: null,
    name: "Administrador Master",
    email: "master@danielaugusto.com",
    role: "administrador-master",
    status: "ativo",
    updatedAt: "19/02/2026, 10:10",
    permissions: buildDefaultPermissions("administrador-master"),
    profile: buildProfile({
      phone: "(85) 98888-0999",
      address: {
        zipCode: "60160-230",
        street: "Av. Santos Dumont",
        number: "2200",
        complement: "Sala 900",
        neighborhood: "Aldeota",
        city: "Fortaleza",
        state: "CE",
        country: "Brasil",
      },
      passwordUpdatedAt: "19/02/2026, 08:10",
    }),
  },
  {
    id: "user-admin",
    tenantId: "tenant-seed",
    name: "Administrador Geral",
    email: "admin@danielaugusto.com",
    role: "administrador",
    status: "ativo",
    updatedAt: "19/02/2026, 10:00",
    permissions: buildDefaultPermissions("administrador"),
    profile: buildProfile({
      phone: "(85) 98888-1000",
      address: {
        zipCode: "60000-001",
        street: "Av. Dom Luis",
        number: "1000",
        complement: "Sala 201",
        neighborhood: "Aldeota",
        city: "Fortaleza",
        state: "CE",
        country: "Brasil",
      },
      passwordUpdatedAt: "19/02/2026, 08:00",
    }),
  },
  {
    id: "user-dados",
    tenantId: "tenant-seed",
    name: "Fernanda Engenharia",
    email: "engenharia@danielaugusto.com",
    role: "gestor-dados",
    status: "ativo",
    updatedAt: "19/02/2026, 09:20",
    permissions: buildDefaultPermissions("gestor-dados"),
    profile: buildProfile({
      phone: "(85) 98888-1001",
      address: {
        zipCode: "60115-080",
        street: "Rua Joaquim Nabuco",
        number: "340",
        complement: "Bloco B",
        neighborhood: "Meireles",
        city: "Fortaleza",
        state: "CE",
        country: "Brasil",
      },
      passwordUpdatedAt: "18/02/2026, 15:40",
    }),
  },
  {
    id: "user-fabrica",
    tenantId: "tenant-seed",
    name: "Marcos Fabrica",
    email: "fabrica@danielaugusto.com",
    role: "gestor-fabrica",
    status: "ativo",
    updatedAt: "19/02/2026, 08:45",
    permissions: buildDefaultPermissions("gestor-fabrica"),
    profile: buildProfile({
      phone: "(85) 98888-1002",
      address: {
        zipCode: "60833-120",
        street: "Rua das Oficinas",
        number: "82",
        complement: "",
        neighborhood: "Distrito Industrial",
        city: "Fortaleza",
        state: "CE",
        country: "Brasil",
      },
      passwordUpdatedAt: "17/02/2026, 11:25",
    }),
  },
  {
    id: "user-chao",
    tenantId: "tenant-seed",
    name: "Equipe Chao",
    email: "chao@danielaugusto.com",
    role: "chao-fabrica",
    status: "ativo",
    updatedAt: "18/02/2026, 17:10",
    permissions: buildDefaultPermissions("chao-fabrica"),
    profile: buildProfile({
      phone: "(85) 98888-1003",
      address: {
        zipCode: "60833-120",
        street: "Rua das Oficinas",
        number: "120",
        complement: "Galpao 3",
        neighborhood: "Distrito Industrial",
        city: "Fortaleza",
        state: "CE",
        country: "Brasil",
      },
      passwordUpdatedAt: "16/02/2026, 10:05",
    }),
  },
  {
    id: "user-loja",
    tenantId: "tenant-seed",
    name: "Rommel Filho",
    email: "loja@danielaugusto.com",
    role: "loja",
    status: "ativo",
    updatedAt: "17/02/2026, 15:45",
    permissions: {
      ...buildDefaultPermissions("loja"),
      "gestor-fabrica.pedidos": "visualizar",
    },
    profile: buildProfile({
      phone: "",
      address: buildEmptyAddress(),
      passwordUpdatedAt: "14/02/2026, 09:00",
    }),
  },
];
